¿Qué es una **matriz**?

Sabemos que es una disposición de número de forma tabular. En Python, usamos listas 2D o arreglos para representar una matriz. Una matriz siempre debe tener un valor numérico.

Lista 1D: es una lista con una fila y muchas columnas, tal como se muestra a continuación.

Lista 2D: es una lista de listas. Puede tener cualquier número de filas y columnas. 


In [1]:
# Método 1 para crear listas 1D y 2D
A = [3,2,-1,9,5]
print(A)
B =[[1,-2,3],[8,4,6],[-6,5,3]]
print(B)

[3, 2, -1, 9, 5]
[[1, -2, 3], [8, 4, 6], [-6, 5, 3]]


La biblioteca **NumPy** proporciona diferentes operaciones especializadas en matrices y proporciona operaciones más rápidas en ellas.

In [2]:
# Método para crear matrices 1D usando NumPy

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# Método 2 para crear matrices 2D usando NumPy

arr_2d =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
type(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [4]:
# Arreglo con elementos de diferentes tipos de datos

arr_2d_1 =np.array([[1,2,3],['a',5,True],[7,8,9]])
print(arr_2d_1)
type(arr_2d_1)

[['1' '2' '3']
 ['a' '5' 'True']
 ['7' '8' '9']]


numpy.ndarray

Accediendo a elementos de listas 2D y matrices

In [5]:
# Accediendo a elementos de una lista 1D o matriz 1D
print(A)
print(A[1])      
print(arr)   
print(arr[2])

[3, 2, -1, 9, 5]
2
[1 2 3 4 5]
3


In [6]:
# Accediendo a elementos de una matriz 2D - Método 1
print(arr_2d)
print(arr_2d[1,2])
# Accediendo a elementos de una matriz 2D - Método 2
print(arr_2d[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
2


Actualizando elementos de listas 2D

In [7]:
# Para actualizar un elemento de una lista/matriz 2D
print(arr_2d)
print('----------------')
# Método 1
arr_2d[1,2]=-4
print(arr_2d)
print('----------------')
# Método 2
arr_2d[1,2]=8
print(arr_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------
[[ 1  2  3]
 [ 4  5 -4]
 [ 7  8  9]]
----------------
[[1 2 3]
 [4 5 8]
 [7 8 9]]


Sumar/restar elementos de listas 2D

In [8]:
# Sumar matrices
a=np.array([[1,3],[5,4]])
b=np.array([[7,8],[6,9]])
rows=2
cols=2
c=np.array([[0,0],[0,0]])
for i in range(rows):
    for j in range(cols):
        c[i][j]=a[i][j]+b[i][j]
print(a,'\n')
print(b,'\n')
print(c)

[[1 3]
 [5 4]] 

[[7 8]
 [6 9]] 

[[ 8 11]
 [11 13]]


In [9]:
# Multiplicación escalar
b=np.array([[2,-2],[0,5],[4,7]])
print(b,'\n')
n=5
mul=np.zeros([3,2])
for i in range(3):
    for j in range(2):
        mul[i][j]=n*b[i][j]
for rows in mul:
    print(rows)

[[ 2 -2]
 [ 0  5]
 [ 4  7]] 

[ 10. -10.]
[ 0. 25.]
[20. 35.]


In [2]:
#Multiplicar elementos de matrices 2d
#matriz 3x3
a=np.array([[2,3,-4],[6,1,0],[8,9,3]])
b=np.array([[2,-2],[0,5],[4,7]])
c=np.zeros([])
print(c,'\n')
rows_a=3
cols_a = rows_b=2
cols_b = 3
for i in range(3):
    for j in range(2):
        for k in range(3):
            c[i][j]=c[i][j]+a[i][k]*b[k][j]
for rows in c : 
    print(rows)            


0.0 



IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [1]:
import numpy as np

q_matrix=np.zeros([6,6])
print(q_matrix)

gama=0.8
def take_action(current_state,reward_matrix,gama):
    action = get_action(current_state,reward_matrix)
    current_sa_reward=reward_matrix[current_state,action]
    print(current_sa_reward)
    q_sa_value=max(q_matrix[action,])
    print(q_sa_value)
    q_current_state=current_sa_reward+(gama*q_sa_value)
    print(q_current_state)
    q_matrix[current_state,action]=q_current_state
    print("Matrix-q","\n",q_matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
def take_action(current_state,reward_matrix,gama):
    action = get_action(current_state,reward_matrix)
    current_sa_reward=reward_matrix[current_state,action]
    print(current_sa_reward)
    q_sa_value=max(q_matrix[action,])
    print(q_sa_value)
    q_current_state=current_sa_reward+(gama*q_sa_value)
    print(q_current_state)
    q_matrix[current_state,action]=q_current_state
    print("Matrix-q","\n",q_matrix)